TOP = ..
MODULES = $(TOP)/modules

include $(TOP)/Makefile.hd

INCLUDES +=	-I$(TOP)/inc\
			-I$(TOP)/video/inc\
			-I$(TOP)/controller/inc\
			-I$(TOP)/modules/mixedAPI/inc\
			-I$(TOP)/modules/llist/inc\
			-I$(TOP)/util

include $(TOP)/Makefile.tl
