# Generic Makefile for compiling objects [header].
include $(TOP)/defines.mk

CC = gcc
CFLAGS += -Wall -Werror

SOURCE = $(wildcard *.c)
OBJS = $(SOURCE:.c=.o)
INCDEP = $(wildcard ./inc/*.h)

INCLUDES = -I./inc

