#ifndef GCONTROLLER_KEYBOARD_DEFINES_HEADER
#define GCONTROLLER_KEYBOARD_DEFINES_HEADER

#define GCONTROLLER_KB_ACTION_INTERVAL_IN_USEC		200*1000				//!< Interval time between reading actions.

#endif /* GCONTROLLER_KEYBOARD_DEFINES_HEADER */
