#ifndef GAMESYSTEM_DEFINES_HEADER
#define GAMESYSTEM_DEFINES_HEADER

/* Media defines. */
#define GAMESYSTEM_COLOR_BITS 32
#define GAMESYSTEM_MAX_X         800
#define GAMESYSTEM_MAX_Y         600
#define GAMESYSTEM_VMAX_X          0
#define GAMESYSTEM_VMAX_Y          0

#define GAMESYSTEM_DIGI_CARD     DIGI_AUTODETECT
#define GAMESYSTEM_MIDI_CARD     MIDI_AUTODETECT

#endif /* SYSTEM_DEFINES_HEADER */
