TOP = ..
MODULES = $(TOP)/modules

include $(TOP)/Makefile.hd

INCLUDES +=	-I$(TOP)/inc\
			-I$(TOP)/video/inc\
			-I$(TOP)/util\
			-I$(MODULES)/mixedAPI/inc\
			-I$(MODULES)/llist/inc

include $(TOP)/Makefile.tl
