TOP = ../..
MODULES = $(TOP)/modules

include $(TOP)/Makefile.hd

INCLUDES +=	-I$(TOP)/inc\
			-I./actions/inc\
			-I$(TOP)/video/inc\
			-I$(TOP)/brain/inc\
			-I$(TOP)/system/inc\
			-I$(TOP)/controller/inc\
			-I$(MODULES)/mixedAPI/inc\
			-I$(MODULES)/llist/inc

include $(TOP)/Makefile.tl
