TOP = ..
MODULES = $(TOP)/modules

include $(TOP)/Makefile.hd

INCLUDES +=	-I$(TOP)/inc\
			-I$(TOP)/util\
			-I$(TOP)/system/inc\
			-I$(MODULES)/mixedAPI/inc\
			-I$(MODULES)/linked_list/inc\
			-I$(MODULES)/alarm/inc

include $(TOP)/Makefile.tl
